Tester

In [19]:
import numpy as np
import pandas as pd

np.random.seed(42)

n_rows = 100

df_clean = pd.DataFrame(
    {
        "feature_a": np.random.normal(loc=0.0, scale=1.0, size=n_rows),
        "feature_b": np.random.uniform(low=0, high=10, size=n_rows),
        "feature_c": np.random.poisson(lam=5, size=n_rows),
        "feature_d": np.random.normal(loc=10.0, scale=2.0, size=n_rows),
        "feature_e": np.random.binomial(n=1, p=0.3, size=n_rows),
    }
)

df_clean.head()

   feature_a  feature_b  feature_c  feature_d  feature_e
0   0.496714   4.174110          6   6.994470          0
1  -0.138264   2.221078          2   9.478530          1
2   0.647689   1.198654          4   7.749162          0
3   1.523030   3.376152          9   9.701927          0
4  -0.234153   9.429097          7   9.986693          0

In [20]:
n_error_rows = 20

# Sample rows from the clean dataframe
df_error = df_clean.sample(n_error_rows, random_state=1).reset_index(drop=True)

# --- Inject errors ---

# Additive constant error
df_error["feature_a"] = df_error["feature_a"] + 2.5

# Scaling error
df_error["feature_b"] = df_error["feature_b"] * 1.8

# Increased noise
df_error["feature_c"] = df_error["feature_c"] + np.random.normal(loc=0, scale=2.0, size=n_error_rows)

# Missing values (randomly drop ~30%)
mask_missing = np.random.rand(n_error_rows) < 0.3
df_error.loc[mask_missing, "feature_d"] = np.nan

# Logical / data-entry error: flip binary with noise
flip_mask = np.random.rand(n_error_rows) < 0.2
df_error.loc[flip_mask, "feature_e"] = 1 - df_error.loc[flip_mask, "feature_e"]

df_error.head()

   feature_a  feature_b  feature_c  feature_d  feature_e
0   2.280328   9.877208   1.254739        NaN          0
1   1.691506  12.819226   7.587316   9.061705          0
2   1.442289   9.643944   3.399279  11.055530          0
3   2.857113  12.454114   1.390426        NaN          0
4   2.172338   6.618884   4.987768   5.260557          0

In [21]:
# cleaner (uses inference)
import pandas as pd

from conformal_data_cleaning.cleaner.autogluon import ConformalAutoGluonCleaner

# Make cleaner
cleaner: ConformalAutoGluonCleaner = ConformalAutoGluonCleaner(confidence_level= 0.999, seed = 42)
fit_cleaner = cleaner.fit(df_clean)
cleaned_data: tuple[pd.DataFrame, pd.DataFrame] = fit_cleaner.transform(df_error)
data, mask = cleaned_data
print((data != df_error).sum())
print(mask.sum())

2025-12-12 12:09:15,897 - INFO - conformal_data_cleaning.cleaner.autogluon: Start fitting predictor #1 of 5
2025-12-12 12:09:15,897 - INFO - conformal_data_cleaning.cleaner.autogluon: Start fitting predictor #1 of 5
Warning: path already exists! This predictor may overwrite an existing predictor! path="AutogluonModels/feature_a"
Verbosity: 2 (Standard Logging)
=================== System Info ===================
AutoGluon Version:  1.4.0
Python Version:     3.12.11
Operating System:   Linux
Platform Machine:   x86_64
Platform Version:   #88~22.04.1-Ubuntu SMP PREEMPT_DYNAMIC Tue Oct 14 14:03:14 UTC 2
CPU Count:          8
Memory Avail:       5.97 GB / 11.46 GB (52.1%)
Disk Space Avail:   124.33 GB / 467.89 GB (26.6%)
===================================================
No presets specified! To achieve strong results with AutoGluon, it is recommended to use the available presets. Defaulting to `'medium'`...
	Recommended Presets (For more details refer to https://auto.gluon.ai/stable/tutorials/tabular/tabular-essentials.html#presets):
	presets='extreme' : New in v1.4: Massively better than 'best' on datasets <30000 samples by using new models meta-learned on https://tabarena.ai: TabPFNv2, TabICL, Mitra, and TabM. Absolute best accuracy. Requires a GPU. Recommended 64 GB CPU memory and 32+ GB GPU memory.
	presets='best'    : Maximize accuracy. Recommended for most users. Use in competitions and benchmarks.
	presets='high'    : Strong accuracy with fast inference speed.
	presets='good'    : Good accuracy with very fast inference speed.
	presets='medium'  : Fast training time, ideal for initial prototyping.
Using hyperparameters preset: hyperparameters='default'
Beginning AutoGluon training ...
AutoGluon will save models to "/home/chandlernick/BHT/Research/conformal-data-cleaning/src/conformal_data_cleaning/AutogluonModels/feature_a"
Train Data Rows:    80
Train Data Columns: 4
Label Column:       feature_a
Problem Type:       quantile
Preprocessing data ...
Using Feature Generators to preprocess the data ...
Fitting AutoMLPipelineFeatureGenerator...
	Available Memory:                    6089.63 MB
	Train Data (Original)  Memory Usage: 0.00 MB (0.0% of available memory)
	Inferring data type of each feature based on column values. Set feature_metadata_in to manually specify special dtypes of the features.
	Stage 1 Generators:
		Fitting AsTypeFeatureGenerator...
			Note: Converting 1 features to boolean dtype as they only contain 2 unique values.
	Stage 2 Generators:
		Fitting FillNaFeatureGenerator...
	Stage 3 Generators:
		Fitting IdentityFeatureGenerator...
	Stage 4 Generators:
		Fitting DropUniqueFeatureGenerator...
	Stage 5 Generators:
		Fitting DropDuplicatesFeatureGenerator...
	Types of features in original data (raw dtype, special dtypes):
		('float', []) : 2 | ['feature_b', 'feature_d']
		('int', [])   : 2 | ['feature_c', 'feature_e']
	Types of features in processed data (raw dtype, special dtypes):
		('float', [])     : 2 | ['feature_b', 'feature_d']
		('int', [])       : 1 | ['feature_c']
		('int', ['bool']) : 1 | ['feature_e']
	0.0s = Fit runtime
	4 features in original data used to generate 4 features in processed data.
	Train Data (Processed) Memory Usage: 0.00 MB (0.0% of available memory)
Data preprocessing and feature engineering runtime = 0.04s ...
AutoGluon will gauge predictive performance using evaluation metric: 'pinball_loss'
	This metric's sign has been flipped to adhere to being higher_is_better. The metric score can be multiplied by -1 to get the metric value.
	To change this, specify the eval_metric parameter of Predictor()
Automatically generating train/validation split with holdout_frac=0.2, Train Rows: 64, Val Rows: 16
User-specified model hyperparameters to be fit:
{
	'NN_TORCH': [{}],
	'GBM': [{'extra_trees': True, 'ag_args': {'name_suffix': 'XT'}}, {}, {'learning_rate': 0.03, 'num_leaves': 128, 'feature_fraction': 0.9, 'min_data_in_leaf': 3, 'ag_args': {'name_suffix': 'Large', 'priority': 0, 'hyperparameter_tune_kwargs': None}}],
	'CAT': [{}],
	'XGB': [{}],
	'FASTAI': [{}],
	'RF': [{'criterion': 'gini', 'ag_args': {'name_suffix': 'Gini', 'problem_types': ['binary', 'multiclass']}}, {'criterion': 'entropy', 'ag_args': {'name_suffix': 'Entr', 'problem_types': ['binary', 'multiclass']}}, {'criterion': 'squared_error', 'ag_args': {'name_suffix': 'MSE', 'problem_types': ['regression', 'quantile']}}],
	'XT': [{'criterion': 'gini', 'ag_args': {'name_suffix': 'Gini', 'problem_types': ['binary', 'multiclass']}}, {'criterion': 'entropy', 'ag_args': {'name_suffix': 'Entr', 'problem_types': ['binary', 'multiclass']}}, {'criterion': 'squared_error', 'ag_args': {'name_suffix': 'MSE', 'problem_types': ['regression', 'quantile']}}],
}
Fitting 8 L1 models, fit_strategy="sequential" ...
Fitting model: LightGBMXT ...
	Failed to import torch or check CUDA availability!Please ensure you have the correct version of PyTorch installed by running `pip install -U torch`
	Fitting with cpus=4, gpus=0, mem=0.0/5.9 GB
	Warning: Exception caused LightGBMXT to fail during training (ImportError)... Skipping this model.
		`import lightgbm` failed. A quick tip is to install via `pip install autogluon.tabular[lightgbm]==1.4.0`.
Fitting model: LightGBM ...
	Failed to import torch or check CUDA availability!Please ensure you have the correct version of PyTorch installed by running `pip install -U torch`
	Fitting with cpus=4, gpus=0, mem=0.0/6.0 GB
	Warning: Exception caused LightGBM to fail during training (ImportError)... Skipping this model.
		`import lightgbm` failed. A quick tip is to install via `pip install autogluon.tabular[lightgbm]==1.4.0`.
Fitting model: RandomForestMSE ...
	Failed to import torch or check CUDA availability!Please ensure you have the correct version of PyTorch installed by running `pip install -U torch`
	Fitting with cpus=8, gpus=0
	WARNING: RandomForestQuantileRegressor are experimental for quantile regression. They may change or be removed without warning in future releases.
	-0.1342	 = Validation score   (-pinball_loss)
	0.33s	 = Training   runtime
	0.03s	 = Validation runtime
Fitting model: CatBoost ...
	Failed to import torch or check CUDA availability!Please ensure you have the correct version of PyTorch installed by running `pip install -U torch`
	Fitting with cpus=4, gpus=0
	Warning: Exception caused CatBoost to fail during training (ImportError)... Skipping this model.
		`import catboost` failed. A quick tip is to install via `pip install autogluon.tabular[catboost]==1.4.0`.
Fitting model: ExtraTreesMSE ...
	Failed to import torch or check CUDA availability!Please ensure you have the correct version of PyTorch installed by running `pip install -U torch`
	Fitting with cpus=8, gpus=0
	WARNING: ExtraTreesQuantileRegressor are experimental for quantile regression. They may change or be removed without warning in future releases.
	-0.1403	 = Validation score   (-pinball_loss)
	0.33s	 = Training   runtime
	0.03s	 = Validation runtime
Fitting model: NeuralNetFastAI ...
	Failed to import torch or check CUDA availability!Please ensure you have the correct version of PyTorch installed by running `pip install -U torch`
	Fitting with cpus=4, gpus=0, mem=0.0/6.1 GB
	Warning: Exception caused NeuralNetFastAI to fail during training (ImportError)... Skipping this model.
		Import fastai failed. A quick tip is to install via `pip install autogluon.tabular[fastai]==1.4.0`.
Fitting model: NeuralNetTorch ...
	Failed to import torch or check CUDA availability!Please ensure you have the correct version of PyTorch installed by running `pip install -U torch`
	Fitting with cpus=4, gpus=0, mem=0.0/6.1 GB
	Warning: Exception caused NeuralNetTorch to fail during training (ImportError)... Skipping this model.
		Unable to import dependency torch
A quick tip is to install via `pip install torch`.
The minimum torch version is currently 2.2.
Fitting model: LightGBMLarge ...
	Failed to import torch or check CUDA availability!Please ensure you have the correct version of PyTorch installed by running `pip install -U torch`
	Fitting with cpus=4, gpus=0, mem=0.0/6.1 GB
	Warning: Exception caused LightGBMLarge to fail during training (ImportError)... Skipping this model.
		`import lightgbm` failed. A quick tip is to install via `pip install autogluon.tabular[lightgbm]==1.4.0`.
Fitting model: WeightedEnsemble_L2 ...
	Failed to import torch or check CUDA availability!Please ensure you have the correct version of PyTorch installed by running `pip install -U torch`
	Ensemble Weights: {'RandomForestMSE': 1.0}
	-0.1342	 = Validation score   (-pinball_loss)
	0.01s	 = Training   runtime
	0.0s	 = Validation runtime
AutoGluon training complete, total runtime = 1.86s ... Best model: WeightedEnsemble_L2 | Estimated inference throughput: 483.2 rows/s (16 batch size)
TabularPredictor saved. To load, use: predictor = TabularPredictor.load("/home/chandlernick/BHT/Research/conformal-data-cleaning/src/conformal_data_cleaning/AutogluonModels/feature_a")
2025-12-12 12:09:17,932 - INFO - conformal_data_cleaning.cleaner.autogluon: Start fitting predictor #2 of 5
2025-12-12 12:09:17,932 - INFO - conformal_data_cleaning.cleaner.autogluon: Start fitting predictor #2 of 5
Warning: path already exists! This predictor may overwrite an existing predictor! path="AutogluonModels/feature_b"
Verbosity: 2 (Standard Logging)
=================== System Info ===================
AutoGluon Version:  1.4.0
Python Version:     3.12.11
Operating System:   Linux
Platform Machine:   x86_64
Platform Version:   #88~22.04.1-Ubuntu SMP PREEMPT_DYNAMIC Tue Oct 14 14:03:14 UTC 2
CPU Count:          8
Memory Avail:       6.06 GB / 11.46 GB (52.9%)
Disk Space Avail:   124.33 GB / 467.89 GB (26.6%)
===================================================
No presets specified! To achieve strong results with AutoGluon, it is recommended to use the available presets. Defaulting to `'medium'`...
	Recommended Presets (For more details refer to https://auto.gluon.ai/stable/tutorials/tabular/tabular-essentials.html#presets):
	presets='extreme' : New in v1.4: Massively better than 'best' on datasets <30000 samples by using new models meta-learned on https://tabarena.ai: TabPFNv2, TabICL, Mitra, and TabM. Absolute best accuracy. Requires a GPU. Recommended 64 GB CPU memory and 32+ GB GPU memory.
	presets='best'    : Maximize accuracy. Recommended for most users. Use in competitions and benchmarks.
	presets='high'    : Strong accuracy with fast inference speed.
	presets='good'    : Good accuracy with very fast inference speed.
	presets='medium'  : Fast training time, ideal for initial prototyping.
Using hyperparameters preset: hyperparameters='default'
Beginning AutoGluon training ...
AutoGluon will save models to "/home/chandlernick/BHT/Research/conformal-data-cleaning/src/conformal_data_cleaning/AutogluonModels/feature_b"
Train Data Rows:    80
Train Data Columns: 4
Label Column:       feature_b
Problem Type:       quantile
Preprocessing data ...
Using Feature Generators to preprocess the data ...
Fitting AutoMLPipelineFeatureGenerator...
	Available Memory:                    6201.20 MB
	Train Data (Original)  Memory Usage: 0.00 MB (0.0% of available memory)
	Inferring data type of each feature based on column values. Set feature_metadata_in to manually specify special dtypes of the features.
	Stage 1 Generators:
		Fitting AsTypeFeatureGenerator...
			Note: Converting 1 features to boolean dtype as they only contain 2 unique values.
	Stage 2 Generators:
		Fitting FillNaFeatureGenerator...
	Stage 3 Generators:
		Fitting IdentityFeatureGenerator...
	Stage 4 Generators:
		Fitting DropUniqueFeatureGenerator...
	Stage 5 Generators:
		Fitting DropDuplicatesFeatureGenerator...
	Types of features in original data (raw dtype, special dtypes):
		('float', []) : 2 | ['feature_a', 'feature_d']
		('int', [])   : 2 | ['feature_c', 'feature_e']
	Types of features in processed data (raw dtype, special dtypes):
		('float', [])     : 2 | ['feature_a', 'feature_d']
		('int', [])       : 1 | ['feature_c']
		('int', ['bool']) : 1 | ['feature_e']
	0.0s = Fit runtime
	4 features in original data used to generate 4 features in processed data.
	Train Data (Processed) Memory Usage: 0.00 MB (0.0% of available memory)
Data preprocessing and feature engineering runtime = 0.03s ...
AutoGluon will gauge predictive performance using evaluation metric: 'pinball_loss'
	This metric's sign has been flipped to adhere to being higher_is_better. The metric score can be multiplied by -1 to get the metric value.
	To change this, specify the eval_metric parameter of Predictor()
Automatically generating train/validation split with holdout_frac=0.2, Train Rows: 64, Val Rows: 16
User-specified model hyperparameters to be fit:
{
	'NN_TORCH': [{}],
	'GBM': [{'extra_trees': True, 'ag_args': {'name_suffix': 'XT'}}, {}, {'learning_rate': 0.03, 'num_leaves': 128, 'feature_fraction': 0.9, 'min_data_in_leaf': 3, 'ag_args': {'name_suffix': 'Large', 'priority': 0, 'hyperparameter_tune_kwargs': None}}],
	'CAT': [{}],
	'XGB': [{}],
	'FASTAI': [{}],
	'RF': [{'criterion': 'gini', 'ag_args': {'name_suffix': 'Gini', 'problem_types': ['binary', 'multiclass']}}, {'criterion': 'entropy', 'ag_args': {'name_suffix': 'Entr', 'problem_types': ['binary', 'multiclass']}}, {'criterion': 'squared_error', 'ag_args': {'name_suffix': 'MSE', 'problem_types': ['regression', 'quantile']}}],
	'XT': [{'criterion': 'gini', 'ag_args': {'name_suffix': 'Gini', 'problem_types': ['binary', 'multiclass']}}, {'criterion': 'entropy', 'ag_args': {'name_suffix': 'Entr', 'problem_types': ['binary', 'multiclass']}}, {'criterion': 'squared_error', 'ag_args': {'name_suffix': 'MSE', 'problem_types': ['regression', 'quantile']}}],
}
Fitting 8 L1 models, fit_strategy="sequential" ...
Fitting model: LightGBMXT ...
	Failed to import torch or check CUDA availability!Please ensure you have the correct version of PyTorch installed by running `pip install -U torch`
	Fitting with cpus=4, gpus=0, mem=0.0/6.1 GB
	Warning: Exception caused LightGBMXT to fail during training (ImportError)... Skipping this model.
		`import lightgbm` failed. A quick tip is to install via `pip install autogluon.tabular[lightgbm]==1.4.0`.
Fitting model: LightGBM ...
	Failed to import torch or check CUDA availability!Please ensure you have the correct version of PyTorch installed by running `pip install -U torch`
	Fitting with cpus=4, gpus=0, mem=0.0/6.1 GB
	Warning: Exception caused LightGBM to fail during training (ImportError)... Skipping this model.
		`import lightgbm` failed. A quick tip is to install via `pip install autogluon.tabular[lightgbm]==1.4.0`.
Fitting model: RandomForestMSE ...
	Failed to import torch or check CUDA availability!Please ensure you have the correct version of PyTorch installed by running `pip install -U torch`
	Fitting with cpus=8, gpus=0
	WARNING: RandomForestQuantileRegressor are experimental for quantile regression. They may change or be removed without warning in future releases.
	-0.4489	 = Validation score   (-pinball_loss)
	0.33s	 = Training   runtime
	0.03s	 = Validation runtime
Fitting model: CatBoost ...
	Failed to import torch or check CUDA availability!Please ensure you have the correct version of PyTorch installed by running `pip install -U torch`
	Fitting with cpus=4, gpus=0
	Warning: Exception caused CatBoost to fail during training (ImportError)... Skipping this model.
		`import catboost` failed. A quick tip is to install via `pip install autogluon.tabular[catboost]==1.4.0`.
Fitting model: ExtraTreesMSE ...
	Failed to import torch or check CUDA availability!Please ensure you have the correct version of PyTorch installed by running `pip install -U torch`
	Fitting with cpus=8, gpus=0
	WARNING: ExtraTreesQuantileRegressor are experimental for quantile regression. They may change or be removed without warning in future releases.
	-0.3906	 = Validation score   (-pinball_loss)
	0.35s	 = Training   runtime
	0.03s	 = Validation runtime
Fitting model: NeuralNetFastAI ...
	Failed to import torch or check CUDA availability!Please ensure you have the correct version of PyTorch installed by running `pip install -U torch`
	Fitting with cpus=4, gpus=0, mem=0.0/6.1 GB
	Warning: Exception caused NeuralNetFastAI to fail during training (ImportError)... Skipping this model.
		Import fastai failed. A quick tip is to install via `pip install autogluon.tabular[fastai]==1.4.0`.
Fitting model: NeuralNetTorch ...
	Failed to import torch or check CUDA availability!Please ensure you have the correct version of PyTorch installed by running `pip install -U torch`
	Fitting with cpus=4, gpus=0, mem=0.0/6.1 GB
	Warning: Exception caused NeuralNetTorch to fail during training (ImportError)... Skipping this model.
		Unable to import dependency torch
A quick tip is to install via `pip install torch`.
The minimum torch version is currently 2.2.
Fitting model: LightGBMLarge ...
	Failed to import torch or check CUDA availability!Please ensure you have the correct version of PyTorch installed by running `pip install -U torch`
	Fitting with cpus=4, gpus=0, mem=0.0/6.1 GB
	Warning: Exception caused LightGBMLarge to fail during training (ImportError)... Skipping this model.
		`import lightgbm` failed. A quick tip is to install via `pip install autogluon.tabular[lightgbm]==1.4.0`.
Fitting model: WeightedEnsemble_L2 ...
	Failed to import torch or check CUDA availability!Please ensure you have the correct version of PyTorch installed by running `pip install -U torch`
	Ensemble Weights: {'ExtraTreesMSE': 0.889, 'RandomForestMSE': 0.111}
	-0.3863	 = Validation score   (-pinball_loss)
	0.01s	 = Training   runtime
	0.0s	 = Validation runtime
AutoGluon training complete, total runtime = 1.82s ... Best model: WeightedEnsemble_L2 | Estimated inference throughput: 241.5 rows/s (16 batch size)
TabularPredictor saved. To load, use: predictor = TabularPredictor.load("/home/chandlernick/BHT/Research/conformal-data-cleaning/src/conformal_data_cleaning/AutogluonModels/feature_b")
2025-12-12 12:09:19,928 - INFO - conformal_data_cleaning.cleaner.autogluon: Start fitting predictor #3 of 5
2025-12-12 12:09:19,928 - INFO - conformal_data_cleaning.cleaner.autogluon: Start fitting predictor #3 of 5
Warning: path already exists! This predictor may overwrite an existing predictor! path="AutogluonModels/feature_c"
Verbosity: 2 (Standard Logging)
=================== System Info ===================
AutoGluon Version:  1.4.0
Python Version:     3.12.11
Operating System:   Linux
Platform Machine:   x86_64
Platform Version:   #88~22.04.1-Ubuntu SMP PREEMPT_DYNAMIC Tue Oct 14 14:03:14 UTC 2
CPU Count:          8
Memory Avail:       6.11 GB / 11.46 GB (53.4%)
Disk Space Avail:   124.33 GB / 467.89 GB (26.6%)
===================================================
No presets specified! To achieve strong results with AutoGluon, it is recommended to use the available presets. Defaulting to `'medium'`...
	Recommended Presets (For more details refer to https://auto.gluon.ai/stable/tutorials/tabular/tabular-essentials.html#presets):
	presets='extreme' : New in v1.4: Massively better than 'best' on datasets <30000 samples by using new models meta-learned on https://tabarena.ai: TabPFNv2, TabICL, Mitra, and TabM. Absolute best accuracy. Requires a GPU. Recommended 64 GB CPU memory and 32+ GB GPU memory.
	presets='best'    : Maximize accuracy. Recommended for most users. Use in competitions and benchmarks.
	presets='high'    : Strong accuracy with fast inference speed.
	presets='good'    : Good accuracy with very fast inference speed.
	presets='medium'  : Fast training time, ideal for initial prototyping.
Using hyperparameters preset: hyperparameters='default'
Beginning AutoGluon training ...
AutoGluon will save models to "/home/chandlernick/BHT/Research/conformal-data-cleaning/src/conformal_data_cleaning/AutogluonModels/feature_c"
Train Data Rows:    80
Train Data Columns: 4
Label Column:       feature_c
Problem Type:       multiclass
Preprocessing data ...

feature_a    17
feature_b    13
feature_c    20
feature_d     9
feature_e     0
dtype: int64
feature_a    17
feature_b    13
feature_c    20
feature_d     9
feature_e     0
dtype: int64

Full Evaluation

In [22]:
import glob
import os

from tab_err.api.high_level import create_errors
from sklearn.ensemble import RandomForestClassifier, RandomForestRegressor
from sklearn.metrics import accuracy_score, mean_squared_error
from sklearn.model_selection import train_test_split
import json


csv_files = glob.glob(os.path.join("./data", "*.csv"))
dataframes = [pd.read_csv(f) for f in csv_files]

In [23]:
for d in dataframes:
    print(d["target"].head())

0    1
1    1
2    1
3    1
4    1
Name: target, dtype: int64
0    good
1     bad
2    good
3    good
4     bad
Name: target, dtype: object
0    1
1    1
2    1
3    1
4    1
Name: target, dtype: int64
0      UP
1      UP
2      UP
3      UP
4    DOWN
Name: target, dtype: object
0    tested_positive
1    tested_negative
2    tested_positive
3    tested_negative
4    tested_positive
Name: target, dtype: object
0    Z
1    P
2    S
3    H
4    H
Name: target, dtype: object
0     van
1     van
2    saab
3     van
4     bus
Name: target, dtype: object

In [24]:
def detect_task(y: pd.Series) -> str:
    """Return 'regression' or 'classification'."""
    # Simple heuristic: numeric with many unique values → regression
    if pd.api.types.is_numeric_dtype(y):
        if y.nunique() > 20:
            return "regression"
        else:
            return "classification"
    else:
        return "classification"

def get_model(task: str):
    return RandomForestRegressor() if task == "regression" else RandomForestClassifier()


def evaluate_model(model, X_test, y_test, task):
    # Predict on test data
    preds = model.predict(X_test)

    if task == "classification":
        acc = accuracy_score(y_test, preds)
        return 1 - acc   # classification error
    else:
        rmse = np.sqrt(mean_squared_error(y_test, preds))
        return rmse      # regression error


def process_dataset(df, cleaner_cls):
    """Run the 3-step pipeline on a single dataframe."""
    df = df.dropna(subset=["target"]).copy()

    # --- 1. Holdout split ---
    clean_df, test_df = train_test_split(df, test_size=0.5, random_state=42)


    X_train = clean_df.drop(columns=["target"])
    y_train = clean_df["target"]


    # Automatically detect regression vs classification
    task = "classification"  #detect_task(y_train)
    model = get_model(task)
    model.fit(X_train, y_train)

    X_test = test_df.drop(columns=["target"])
    y_test = test_df["target"]



    # -------------------------
    # A) Baseline model
    # -------------------------
    baseline_err = evaluate_model(model, X_test, y_test, task)

    # -------------------------
    # B) Error features model
    # -------------------------

    # Tab err HLA
    X_test_errored, _ = create_errors(X_test, error_rate=0.5)

    error_features_err = evaluate_model(model, X_test_errored, y_test, task)

    # -------------------------
    # C) Cleaned model
    # -------------------------
    cleaner = cleaner_cls(confidence_level=0.999, seed=42)

    # Fit cleaner on holdout data (df_error)
    fit_cleaner = cleaner.fit(X_train)
    X_test_cleaned, _ = fit_cleaner.transform(X_test_errored)


    cleaned_err = evaluate_model(model, X_test_cleaned, y_test, task)

    return {
        "baseline_error": baseline_err,
        "error_features_error": error_features_err,
        "cleaned_error": cleaned_err,
        "task": task,
    }

def evaluate_all(dfs, cleaner_cls):
    results = []
    for i, df in enumerate(dfs):
        print(f"Processing dataset {i+1}/{len(dfs)} ...")
        res = process_dataset(df, cleaner_cls)
        results.append(res)
        with open(f"{i}.json", "w") as f:
            json.dump(res, f, indent=2)

    return pd.DataFrame(results)

In [25]:
results = evaluate_all(dataframes, ConformalAutoGluonCleaner)
print(results)

Processing dataset 1/7 ...

/home/chandlernick/BHT/Research/conformal-data-cleaning/.venv/lib/python3.12/site-packages/tab_err/error_type/_error_type.py:67: UserWarning: self.config.add_delta_value is none, sampling a random delta value uniformly from the range of column: word_freq_make.
  return self._apply(data, error_mask, column)
/home/chandlernick/BHT/Research/conformal-data-cleaning/.venv/lib/python3.12/site-packages/tab_err/error_type/_error_type.py:67: UserWarning: No scaling function was supplied for WrongUnit, defaulting to multiplication by 10.0.
  return self._apply(data, error_mask, column)
2025-12-12 12:09:29,639 - INFO - conformal_data_cleaning.cleaner.autogluon: Start fitting predictor #1 of 57
2025-12-12 12:09:29,639 - INFO - conformal_data_cleaning.cleaner.autogluon: Start fitting predictor #1 of 57
Warning: path already exists! This predictor may overwrite an existing predictor! path="AutogluonModels/word_freq_make"
Verbosity: 2 (Standard Logging)
=================== System Info ===================
AutoGluon Version:  1.4.0
Python Version:     3.12.11
Operating System:   Linux
Platform Machine:   x86_64
Platform Version:   #88~22.04.1-Ubuntu SMP PREEMPT_DYNAMIC Tue Oct 14 14:03:14 UTC 2
CPU Count:          8
Memory Avail:       5.83 GB / 11.46 GB (50.9%)
Disk Space Avail:   124.33 GB / 467.89 GB (26.6%)
===================================================
No presets specified! To achieve strong results with AutoGluon, it is recommended to use the available presets. Defaulting to `'medium'`...
	Recommended Presets (For more details refer to https://auto.gluon.ai/stable/tutorials/tabular/tabular-essentials.html#presets):
	presets='extreme' : New in v1.4: Massively better than 'best' on datasets <30000 samples by using new models meta-learned on https://tabarena.ai: TabPFNv2, TabICL, Mitra, and TabM. Absolute best accuracy. Requires a GPU. Recommended 64 GB CPU memory and 32+ GB GPU memory.
	presets='best'    : Maximize accuracy. Recommended for most users. Use in competitions and benchmarks.
	presets='high'    : Strong accuracy with fast inference speed.
	presets='good'    : Good accuracy with very fast inference speed.
	presets='medium'  : Fast training time, ideal for initial prototyping.
Using hyperparameters preset: hyperparameters='default'
Beginning AutoGluon training ...
AutoGluon will save models to "/home/chandlernick/BHT/Research/conformal-data-cleaning/src/conformal_data_cleaning/AutogluonModels/word_freq_make"
Train Data Rows:    1840
Train Data Columns: 56
Label Column:       word_freq_make
Problem Type:       multiclass
Preprocessing data ...
Warning: Updated label_count_threshold from 10 to 2 to avoid cutting too many classes.
Warning: Some classes in the training set have fewer than 2 examples. AutoGluon will only keep 79 out of 122 classes for training and will not try to predict the rare classes. To keep more classes, increase the number of datapoints from these rare classes in the training data or reduce label_count_threshold.
Fraction of data from classes with at least 2 examples that will be kept for training models: 0.9766304347826087
Train Data Class Count: 79
Using Feature Generators to preprocess the data ...
Fitting AutoMLPipelineFeatureGenerator...
	Available Memory:                    5984.85 MB
	Train Data (Original)  Memory Usage: 0.77 MB (0.0% of available memory)
	Inferring data type of each feature based on column values. Set feature_metadata_in to manually specify special dtypes of the features.
	Stage 1 Generators:
		Fitting AsTypeFeatureGenerator...
	Stage 2 Generators:
		Fitting FillNaFeatureGenerator...
	Stage 3 Generators:
		Fitting IdentityFeatureGenerator...
	Stage 4 Generators:
		Fitting DropUniqueFeatureGenerator...
	Stage 5 Generators:
		Fitting DropDuplicatesFeatureGenerator...
	Types of features in original data (raw dtype, special dtypes):
		('float', []) : 54 | ['word_freq_address', 'word_freq_all', 'word_freq_3d', 'word_freq_our', 'word_freq_over', ...]
		('int', [])   :  2 | ['capital_run_length_longest', 'capital_run_length_total']
	Types of features in processed data (raw dtype, special dtypes):
		('float', []) : 54 | ['word_freq_address', 'word_freq_all', 'word_freq_3d', 'word_freq_our', 'word_freq_over', ...]
		('int', [])   :  2 | ['capital_run_length_longest', 'capital_run_length_total']
	0.0s = Fit runtime
	56 features in original data used to generate 56 features in processed data.
	Train Data (Processed) Memory Usage: 0.77 MB (0.0% of available memory)
Data preprocessing and feature engineering runtime = 0.05s ...
AutoGluon will gauge predictive performance using evaluation metric: 'f1_macro'
	To change this, specify the eval_metric parameter of Predictor()
Automatically generating train/validation split with holdout_frac=0.2, Train Rows: 1437, Val Rows: 360
User-specified model hyperparameters to be fit:
{
	'NN_TORCH': [{}],
	'GBM': [{'extra_trees': True, 'ag_args': {'name_suffix': 'XT'}}, {}, {'learning_rate': 0.03, 'num_leaves': 128, 'feature_fraction': 0.9, 'min_data_in_leaf': 3, 'ag_args': {'name_suffix': 'Large', 'priority': 0, 'hyperparameter_tune_kwargs': None}}],
	'CAT': [{}],
	'XGB': [{}],
	'FASTAI': [{}],
	'RF': [{'criterion': 'gini', 'ag_args': {'name_suffix': 'Gini', 'problem_types': ['binary', 'multiclass']}}, {'criterion': 'entropy', 'ag_args': {'name_suffix': 'Entr', 'problem_types': ['binary', 'multiclass']}}, {'criterion': 'squared_error', 'ag_args': {'name_suffix': 'MSE', 'problem_types': ['regression', 'quantile']}}],
	'XT': [{'criterion': 'gini', 'ag_args': {'name_suffix': 'Gini', 'problem_types': ['binary', 'multiclass']}}, {'criterion': 'entropy', 'ag_args': {'name_suffix': 'Entr', 'problem_types': ['binary', 'multiclass']}}, {'criterion': 'squared_error', 'ag_args': {'name_suffix': 'MSE', 'problem_types': ['regression', 'quantile']}}],
}
Fitting 11 L1 models, fit_strategy="sequential" ...
Fitting model: NeuralNetFastAI ...
	Failed to import torch or check CUDA availability!Please ensure you have the correct version of PyTorch installed by running `pip install -U torch`
	Fitting with cpus=4, gpus=0, mem=0.0/5.8 GB
	Warning: Exception caused NeuralNetFastAI to fail during training (ImportError)... Skipping this model.
		Import fastai failed. A quick tip is to install via `pip install autogluon.tabular[fastai]==1.4.0`.
Fitting model: LightGBMXT ...
	Failed to import torch or check CUDA availability!Please ensure you have the correct version of PyTorch installed by running `pip install -U torch`
	Fitting with cpus=4, gpus=0, mem=0.3/5.9 GB
	Warning: Exception caused LightGBMXT to fail during training (ImportError)... Skipping this model.
		`import lightgbm` failed. A quick tip is to install via `pip install autogluon.tabular[lightgbm]==1.4.0`.
Fitting model: LightGBM ...
	Failed to import torch or check CUDA availability!Please ensure you have the correct version of PyTorch installed by running `pip install -U torch`
	Fitting with cpus=4, gpus=0, mem=0.3/5.8 GB
	Warning: Exception caused LightGBM to fail during training (ImportError)... Skipping this model.
		`import lightgbm` failed. A quick tip is to install via `pip install autogluon.tabular[lightgbm]==1.4.0`.
Fitting model: RandomForestGini ...
	Failed to import torch or check CUDA availability!Please ensure you have the correct version of PyTorch installed by running `pip install -U torch`
	Fitting with cpus=8, gpus=0, mem=0.1/5.8 GB
	0.2033	 = Validation score   (f1_macro)
	2.7s	 = Training   runtime
	0.04s	 = Validation runtime
Fitting model: RandomForestEntr ...
	Failed to import torch or check CUDA availability!Please ensure you have the correct version of PyTorch installed by running `pip install -U torch`
	Fitting with cpus=8, gpus=0, mem=0.1/5.7 GB
	0.2033	 = Validation score   (f1_macro)
	2.92s	 = Training   runtime
	0.04s	 = Validation runtime
Fitting model: CatBoost ...
	Failed to import torch or check CUDA availability!Please ensure you have the correct version of PyTorch installed by running `pip install -U torch`
	Fitting with cpus=4, gpus=0
	Warning: Exception caused CatBoost to fail during training (ImportError)... Skipping this model.
		`import catboost` failed. A quick tip is to install via `pip install autogluon.tabular[catboost]==1.4.0`.
Fitting model: ExtraTreesGini ...
	Failed to import torch or check CUDA availability!Please ensure you have the correct version of PyTorch installed by running `pip install -U torch`
	Fitting with cpus=8, gpus=0, mem=0.1/5.5 GB
	0.2057	 = Validation score   (f1_macro)
	2.52s	 = Training   runtime
	0.04s	 = Validation runtime
Fitting model: ExtraTreesEntr ...
	Failed to import torch or check CUDA availability!Please ensure you have the correct version of PyTorch installed by running `pip install -U torch`
	Fitting with cpus=8, gpus=0, mem=0.1/5.7 GB
	0.2057	 = Validation score   (f1_macro)
	2.55s	 = Training   runtime
	0.04s	 = Validation runtime
Fitting model: XGBoost ...
	Failed to import torch or check CUDA availability!Please ensure you have the correct version of PyTorch installed by running `pip install -U torch`
	Fitting with cpus=4, gpus=0
	Warning: Exception caused XGBoost to fail during training (ImportError)... Skipping this model.
		`import xgboost` failed. A quick tip is to install via `pip install autogluon.tabular[xgboost]==1.4.0`.
Fitting model: NeuralNetTorch ...
	Failed to import torch or check CUDA availability!Please ensure you have the correct version of PyTorch installed by running `pip install -U torch`
	Fitting with cpus=4, gpus=0, mem=0.0/5.8 GB
	Warning: Exception caused NeuralNetTorch to fail during training (ImportError)... Skipping this model.
		Unable to import dependency torch
A quick tip is to install via `pip install torch`.
The minimum torch version is currently 2.2.
Fitting model: LightGBMLarge ...
	Failed to import torch or check CUDA availability!Please ensure you have the correct version of PyTorch installed by running `pip install -U torch`
	Fitting with cpus=4, gpus=0, mem=1.0/5.8 GB
	Warning: Exception caused LightGBMLarge to fail during training (ImportError)... Skipping this model.
		`import lightgbm` failed. A quick tip is to install via `pip install autogluon.tabular[lightgbm]==1.4.0`.
Fitting model: WeightedEnsemble_L2 ...
	Failed to import torch or check CUDA availability!Please ensure you have the correct version of PyTorch installed by running `pip install -U torch`
	Ensemble Weights: {'ExtraTreesGini': 1.0}
	0.2057	 = Validation score   (f1_macro)
	0.12s	 = Training   runtime
	0.0s	 = Validation runtime
AutoGluon training complete, total runtime = 13.16s ... Best model: WeightedEnsemble_L2 | Estimated inference throughput: 8047.7 rows/s (360 batch size)
TabularPredictor saved. To load, use: predictor = TabularPredictor.load("/home/chandlernick/BHT/Research/conformal-data-cleaning/src/conformal_data_cleaning/AutogluonModels/word_freq_make")
2025-12-12 12:09:43,084 - INFO - conformal_data_cleaning.cleaner.autogluon: Start fitting predictor #2 of 57
2025-12-12 12:09:43,084 - INFO - conformal_data_cleaning.cleaner.autogluon: Start fitting predictor #2 of 57
Warning: path already exists! This predictor may overwrite an existing predictor! path="AutogluonModels/word_freq_address"
Verbosity: 2 (Standard Logging)
=================== System Info ===================
AutoGluon Version:  1.4.0
Python Version:     3.12.11
Operating System:   Linux
Platform Machine:   x86_64
Platform Version:   #88~22.04.1-Ubuntu SMP PREEMPT_DYNAMIC Tue Oct 14 14:03:14 UTC 2
CPU Count:          8
Memory Avail:       5.81 GB / 11.46 GB (50.7%)
Disk Space Avail:   124.33 GB / 467.89 GB (26.6%)
===================================================
No presets specified! To achieve strong results with AutoGluon, it is recommended to use the available presets. Defaulting to `'medium'`...
	Recommended Presets (For more details refer to https://auto.gluon.ai/stable/tutorials/tabular/tabular-essentials.html#presets):
	presets='extreme' : New in v1.4: Massively better than 'best' on datasets <30000 samples by using new models meta-learned on https://tabarena.ai: TabPFNv2, TabICL, Mitra, and TabM. Absolute best accuracy. Requires a GPU. Recommended 64 GB CPU memory and 32+ GB GPU memory.
	presets='best'    : Maximize accuracy. Recommended for most users. Use in competitions and benchmarks.
	presets='high'    : Strong accuracy with fast inference speed.
	presets='good'    : Good accuracy with very fast inference speed.
	presets='medium'  : Fast training time, ideal for initial prototyping.
Using hyperparameters preset: hyperparameters='default'
Beginning AutoGluon training ...
AutoGluon will save models to "/home/chandlernick/BHT/Research/conformal-data-cleaning/src/conformal_data_cleaning/AutogluonModels/word_freq_address"
Train Data Rows:    1840
Train Data Columns: 56
Label Column:       word_freq_address
Problem Type:       multiclass
Preprocessing data ...
Warning: Updated label_count_threshold from 10 to 1 to avoid cutting too many classes.
Train Data Class Count: 121
Using Feature Generators to preprocess the data ...
Fitting AutoMLPipelineFeatureGenerator...
	Available Memory:                    5947.79 MB
	Train Data (Original)  Memory Usage: 0.79 MB (0.0% of available memory)
	Inferring data type of each feature based on column values. Set feature_metadata_in to manually specify special dtypes of the features.
	Stage 1 Generators:
		Fitting AsTypeFeatureGenerator...
	Stage 2 Generators:
		Fitting FillNaFeatureGenerator...
	Stage 3 Generators:
		Fitting IdentityFeatureGenerator...
	Stage 4 Generators:
		Fitting DropUniqueFeatureGenerator...
	Stage 5 Generators:
		Fitting DropDuplicatesFeatureGenerator...
	Types of features in original data (raw dtype, special dtypes):
		('float', []) : 54 | ['word_freq_make', 'word_freq_all', 'word_freq_3d', 'word_freq_our', 'word_freq_over', ...]
		('int', [])   :  2 | ['capital_run_length_longest', 'capital_run_length_total']
	Types of features in processed data (raw dtype, special dtypes):
		('float', []) : 54 | ['word_freq_make', 'word_freq_all', 'word_freq_3d', 'word_freq_our', 'word_freq_over', ...]
		('int', [])   :  2 | ['capital_run_length_longest', 'capital_run_length_total']
	0.0s = Fit runtime
	56 features in original data used to generate 56 features in processed data.
	Train Data (Processed) Memory Usage: 0.79 MB (0.0% of available memory)
Data preprocessing and feature engineering runtime = 0.05s ...
AutoGluon will gauge predictive performance using evaluation metric: 'f1_macro'
	To change this, specify the eval_metric parameter of Predictor()
Automatically generating train/validation split with holdout_frac=0.2, Train Rows: 1482, Val Rows: 358
User-specified model hyperparameters to be fit:
{
	'NN_TORCH': [{}],
	'GBM': [{'extra_trees': True, 'ag_args': {'name_suffix': 'XT'}}, {}, {'learning_rate': 0.03, 'num_leaves': 128, 'feature_fraction': 0.9, 'min_data_in_leaf': 3, 'ag_args': {'name_suffix': 'Large', 'priority': 0, 'hyperparameter_tune_kwargs': None}}],
	'CAT': [{}],
	'XGB': [{}],
	'FASTAI': [{}],
	'RF': [{'criterion': 'gini', 'ag_args': {'name_suffix': 'Gini', 'problem_types': ['binary', 'multiclass']}}, {'criterion': 'entropy', 'ag_args': {'name_suffix': 'Entr', 'problem_types': ['binary', 'multiclass']}}, {'criterion': 'squared_error', 'ag_args': {'name_suffix': 'MSE', 'problem_types': ['regression', 'quantile']}}],
	'XT': [{'criterion': 'gini', 'ag_args': {'name_suffix': 'Gini', 'problem_types': ['binary', 'multiclass']}}, {'criterion': 'entropy', 'ag_args': {'name_suffix': 'Entr', 'problem_types': ['binary', 'multiclass']}}, {'criterion': 'squared_error', 'ag_args': {'name_suffix': 'MSE', 'problem_types': ['regression', 'quantile']}}],
}
Fitting 11 L1 models, fit_strategy="sequential" ...
Fitting model: NeuralNetFastAI ...
	Failed to import torch or check CUDA availability!Please ensure you have the correct version of PyTorch installed by running `pip install -U torch`
	Fitting with cpus=4, gpus=0, mem=0.0/5.8 GB
	Warning: Exception caused NeuralNetFastAI to fail during training (ImportError)... Skipping this model.
		Import fastai failed. A quick tip is to install via `pip install autogluon.tabular[fastai]==1.4.0`.
Fitting model: LightGBMXT ...
	Failed to import torch or check CUDA availability!Please ensure you have the correct version of PyTorch installed by running `pip install -U torch`
	Fitting with cpus=4, gpus=0, mem=0.4/5.8 GB
	Warning: Exception caused LightGBMXT to fail during training (ImportError)... Skipping this model.
		`import lightgbm` failed. A quick tip is to install via `pip install autogluon.tabular[lightgbm]==1.4.0`.
Fitting model: LightGBM ...
	Failed to import torch or check CUDA availability!Please ensure you have the correct version of PyTorch installed by running `pip install -U torch`
	Fitting with cpus=4, gpus=0, mem=0.4/5.8 GB
	Warning: Exception caused LightGBM to fail during training (ImportError)... Skipping this model.
		`import lightgbm` failed. A quick tip is to install via `pip install autogluon.tabular[lightgbm]==1.4.0`.
Fitting model: RandomForestGini ...
	Failed to import torch or check CUDA availability!Please ensure you have the correct version of PyTorch installed by running `pip install -U torch`
	Fitting with cpus=8, gpus=0, mem=0.1/5.8 GB
	0.3283	 = Validation score   (f1_macro)
	3.57s	 = Training   runtime
	0.04s	 = Validation runtime
Fitting model: RandomForestEntr ...
	Failed to import torch or check CUDA availability!Please ensure you have the correct version of PyTorch installed by running `pip install -U torch`
	Fitting with cpus=8, gpus=0, mem=0.1/5.6 GB
	0.3283	 = Validation score   (f1_macro)
	3.6s	 = Training   runtime
	0.05s	 = Validation runtime
Fitting model: CatBoost ...
	Failed to import torch or check CUDA availability!Please ensure you have the correct version of PyTorch installed by running `pip install -U torch`
	Fitting with cpus=4, gpus=0
	Warning: Exception caused CatBoost to fail during training (ImportError)... Skipping this model.
		`import catboost` failed. A quick tip is to install via `pip install autogluon.tabular[catboost]==1.4.0`.
Fitting model: ExtraTreesGini ...
	Failed to import torch or check CUDA availability!Please ensure you have the correct version of PyTorch installed by running `pip install -U torch`
	Fitting with cpus=8, gpus=0, mem=0.1/5.8 GB
	0.3283	 = Validation score   (f1_macro)
	3.46s	 = Training   runtime
	0.04s	 = Validation runtime
Fitting model: ExtraTreesEntr ...
	Failed to import torch or check CUDA availability!Please ensure you have the correct version of PyTorch installed by running `pip install -U torch`
	Fitting with cpus=8, gpus=0, mem=0.1/5.8 GB

KeyboardInterrupt: