Tester

In [1]:
import numpy as np
import pandas as pd

np.random.seed(42)

n_rows = 100

df_clean = pd.DataFrame({
    "feature_a": np.random.normal(loc=0.0, scale=1.0, size=n_rows),
    "feature_b": np.random.uniform(low=0, high=10, size=n_rows),
    "feature_c": np.random.poisson(lam=5, size=n_rows),
    "feature_d": np.random.normal(loc=10.0, scale=2.0, size=n_rows),
    "feature_e": np.random.binomial(n=1, p=0.3, size=n_rows),
})

df_clean.head()

   feature_a  feature_b  feature_c  feature_d  feature_e
0   0.496714   4.174110          6   6.994470          0
1  -0.138264   2.221078          2   9.478530          1
2   0.647689   1.198654          4   7.749162          0
3   1.523030   3.376152          9   9.701927          0
4  -0.234153   9.429097          7   9.986693          0

In [2]:
n_error_rows = 20

# Sample rows from the clean dataframe
df_error = df_clean.sample(n_error_rows, random_state=1).reset_index(drop=True)

# --- Inject errors ---

# Additive constant error
df_error["feature_a"] = df_error["feature_a"] + 2.5

# Scaling error
df_error["feature_b"] = df_error["feature_b"] * 1.8

# Increased noise
df_error["feature_c"] = df_error["feature_c"] + np.random.normal(
    loc=0, scale=2.0, size=n_error_rows
)

# Missing values (randomly drop ~30%)
mask_missing = np.random.rand(n_error_rows) < 0.3
df_error.loc[mask_missing, "feature_d"] = np.nan

# Logical / data-entry error: flip binary with noise
flip_mask = np.random.rand(n_error_rows) < 0.2
df_error.loc[flip_mask, "feature_e"] = 1 - df_error.loc[flip_mask, "feature_e"]

df_error.head()

   feature_a  feature_b  feature_c  feature_d  feature_e
0   2.280328   9.877208   1.254739        NaN          0
1   1.691506  12.819226   7.587316   9.061705          0
2   1.442289   9.643944   3.399279  11.055530          0
3   2.857113  12.454114   1.390426        NaN          0
4   2.172338   6.618884   4.987768   5.260557          0

In [3]:
# cleaner (uses inference)
import pandas as pd

from conformal_data_cleaning.cleaner.autogluon import ConformalAutoGluonCleaner

# Make cleaner
cleaner: ConformalAutoGluonCleaner = ConformalAutoGluonCleaner(confidence_level= 0.999, seed = 42)


# Do
fit_cleaner = cleaner.fit(df_clean)

cleaned_data: tuple[pd.DataFrame, pd.DataFrame] = fit_cleaner.transform(df_error)

/home/chandlernick/BHT/Research/conformal-data-cleaning/.venv/lib/python3.12/site-packages/tqdm/auto.py:21: TqdmWarning: IProgress not found. Please update jupyter and ipywidgets. See https://ipywidgets.readthedocs.io/en/stable/user_install.html
  from .autonotebook import tqdm as notebook_tqdm
2025-12-10 10:05:00,950 - INFO - conformal_data_cleaning.cleaner.autogluon: Start fitting predictor #1 of 5
2025-12-10 10:05:00,950 - INFO - conformal_data_cleaning.cleaner.autogluon: Start fitting predictor #1 of 5
Warning: path already exists! This predictor may overwrite an existing predictor! path="AutogluonModels/feature_a"
Verbosity: 2 (Standard Logging)
=================== System Info ===================
AutoGluon Version:  1.4.0
Python Version:     3.12.11
Operating System:   Linux
Platform Machine:   x86_64
Platform Version:   #88~22.04.1-Ubuntu SMP PREEMPT_DYNAMIC Tue Oct 14 14:03:14 UTC 2
CPU Count:          8
Memory Avail:       4.59 GB / 11.46 GB (40.0%)
Disk Space Avail:   155.50 GB / 467.89 GB (33.2%)
===================================================
No presets specified! To achieve strong results with AutoGluon, it is recommended to use the available presets. Defaulting to `'medium'`...
	Recommended Presets (For more details refer to https://auto.gluon.ai/stable/tutorials/tabular/tabular-essentials.html#presets):
	presets='extreme' : New in v1.4: Massively better than 'best' on datasets <30000 samples by using new models meta-learned on https://tabarena.ai: TabPFNv2, TabICL, Mitra, and TabM. Absolute best accuracy. Requires a GPU. Recommended 64 GB CPU memory and 32+ GB GPU memory.
	presets='best'    : Maximize accuracy. Recommended for most users. Use in competitions and benchmarks.
	presets='high'    : Strong accuracy with fast inference speed.
	presets='good'    : Good accuracy with very fast inference speed.
	presets='medium'  : Fast training time, ideal for initial prototyping.
Using hyperparameters preset: hyperparameters='default'
Beginning AutoGluon training ...
AutoGluon will save models to "/home/chandlernick/BHT/Research/conformal-data-cleaning/src/conformal_data_cleaning/AutogluonModels/feature_a"
Train Data Rows:    80
Train Data Columns: 4
Label Column:       feature_a
Problem Type:       quantile
Preprocessing data ...
Using Feature Generators to preprocess the data ...
Fitting AutoMLPipelineFeatureGenerator...
	Available Memory:                    4693.74 MB
	Train Data (Original)  Memory Usage: 0.00 MB (0.0% of available memory)
	Inferring data type of each feature based on column values. Set feature_metadata_in to manually specify special dtypes of the features.
	Stage 1 Generators:
		Fitting AsTypeFeatureGenerator...
			Note: Converting 1 features to boolean dtype as they only contain 2 unique values.
	Stage 2 Generators:
		Fitting FillNaFeatureGenerator...
	Stage 3 Generators:
		Fitting IdentityFeatureGenerator...
	Stage 4 Generators:
		Fitting DropUniqueFeatureGenerator...
	Stage 5 Generators:
		Fitting DropDuplicatesFeatureGenerator...
	Types of features in original data (raw dtype, special dtypes):
		('float', []) : 2 | ['feature_b', 'feature_d']
		('int', [])   : 2 | ['feature_c', 'feature_e']
	Types of features in processed data (raw dtype, special dtypes):
		('float', [])     : 2 | ['feature_b', 'feature_d']
		('int', [])       : 1 | ['feature_c']
		('int', ['bool']) : 1 | ['feature_e']
	0.0s = Fit runtime
	4 features in original data used to generate 4 features in processed data.
	Train Data (Processed) Memory Usage: 0.00 MB (0.0% of available memory)
Data preprocessing and feature engineering runtime = 0.02s ...
AutoGluon will gauge predictive performance using evaluation metric: 'pinball_loss'
	This metric's sign has been flipped to adhere to being higher_is_better. The metric score can be multiplied by -1 to get the metric value.
	To change this, specify the eval_metric parameter of Predictor()
Automatically generating train/validation split with holdout_frac=0.2, Train Rows: 64, Val Rows: 16
User-specified model hyperparameters to be fit:
{
	'NN_TORCH': [{}],
	'GBM': [{'extra_trees': True, 'ag_args': {'name_suffix': 'XT'}}, {}, {'learning_rate': 0.03, 'num_leaves': 128, 'feature_fraction': 0.9, 'min_data_in_leaf': 3, 'ag_args': {'name_suffix': 'Large', 'priority': 0, 'hyperparameter_tune_kwargs': None}}],
	'CAT': [{}],
	'XGB': [{}],
	'FASTAI': [{}],
	'RF': [{'criterion': 'gini', 'ag_args': {'name_suffix': 'Gini', 'problem_types': ['binary', 'multiclass']}}, {'criterion': 'entropy', 'ag_args': {'name_suffix': 'Entr', 'problem_types': ['binary', 'multiclass']}}, {'criterion': 'squared_error', 'ag_args': {'name_suffix': 'MSE', 'problem_types': ['regression', 'quantile']}}],
	'XT': [{'criterion': 'gini', 'ag_args': {'name_suffix': 'Gini', 'problem_types': ['binary', 'multiclass']}}, {'criterion': 'entropy', 'ag_args': {'name_suffix': 'Entr', 'problem_types': ['binary', 'multiclass']}}, {'criterion': 'squared_error', 'ag_args': {'name_suffix': 'MSE', 'problem_types': ['regression', 'quantile']}}],
}
Fitting 8 L1 models, fit_strategy="sequential" ...
Fitting model: LightGBMXT ...
	Failed to import torch or check CUDA availability!Please ensure you have the correct version of PyTorch installed by running `pip install -U torch`
	Fitting with cpus=4, gpus=0, mem=0.0/4.6 GB
	Warning: Exception caused LightGBMXT to fail during training (ImportError)... Skipping this model.
		`import lightgbm` failed. A quick tip is to install via `pip install autogluon.tabular[lightgbm]==1.4.0`.
Fitting model: LightGBM ...
	Failed to import torch or check CUDA availability!Please ensure you have the correct version of PyTorch installed by running `pip install -U torch`
	Fitting with cpus=4, gpus=0, mem=0.0/4.6 GB
	Warning: Exception caused LightGBM to fail during training (ImportError)... Skipping this model.
		`import lightgbm` failed. A quick tip is to install via `pip install autogluon.tabular[lightgbm]==1.4.0`.

[('preprocess', ColumnTransformer(sparse_threshold=0,
                  transformers=[('categorical_features',
                                 OneHotEncoder(handle_unknown='ignore'),
                                 ['feature_c', 'feature_e']),
                                ('scaled_numeric', StandardScaler(),
                                 ['feature_a', 'feature_b', 'feature_d'])])), ('predictor', <autogluon.tabular.predictor.predictor.TabularPredictor object at 0x700920eac6b0>)]

Fitting model: RandomForestMSE ...
	Failed to import torch or check CUDA availability!Please ensure you have the correct version of PyTorch installed by running `pip install -U torch`
	Fitting with cpus=8, gpus=0
	WARNING: RandomForestQuantileRegressor are experimental for quantile regression. They may change or be removed without warning in future releases.
	-0.1342	 = Validation score   (-pinball_loss)
	0.36s	 = Training   runtime
	0.03s	 = Validation runtime
Fitting model: CatBoost ...
	Failed to import torch or check CUDA availability!Please ensure you have the correct version of PyTorch installed by running `pip install -U torch`
	Fitting with cpus=4, gpus=0
	Warning: Exception caused CatBoost to fail during training (ImportError)... Skipping this model.
		`import catboost` failed. A quick tip is to install via `pip install autogluon.tabular[catboost]==1.4.0`.
Fitting model: ExtraTreesMSE ...
	Failed to import torch or check CUDA availability!Please ensure you have the correct version of PyTorch installed by running `pip install -U torch`
	Fitting with cpus=8, gpus=0
	WARNING: ExtraTreesQuantileRegressor are experimental for quantile regression. They may change or be removed without warning in future releases.
	-0.1403	 = Validation score   (-pinball_loss)
	0.32s	 = Training   runtime
	0.03s	 = Validation runtime
Fitting model: NeuralNetFastAI ...
	Failed to import torch or check CUDA availability!Please ensure you have the correct version of PyTorch installed by running `pip install -U torch`
	Fitting with cpus=4, gpus=0, mem=0.0/4.6 GB
	Warning: Exception caused NeuralNetFastAI to fail during training (ImportError)... Skipping this model.
		Import fastai failed. A quick tip is to install via `pip install autogluon.tabular[fastai]==1.4.0`.
Fitting model: NeuralNetTorch ...
	Failed to import torch or check CUDA availability!Please ensure you have the correct version of PyTorch installed by running `pip install -U torch`
	Fitting with cpus=4, gpus=0, mem=0.0/4.6 GB
	Warning: Exception caused NeuralNetTorch to fail during training (ImportError)... Skipping this model.
		Unable to import dependency torch
A quick tip is to install via `pip install torch`.
The minimum torch version is currently 2.2.
Fitting model: LightGBMLarge ...
	Failed to import torch or check CUDA availability!Please ensure you have the correct version of PyTorch installed by running `pip install -U torch`
	Fitting with cpus=4, gpus=0, mem=0.0/4.6 GB
	Warning: Exception caused LightGBMLarge to fail during training (ImportError)... Skipping this model.
		`import lightgbm` failed. A quick tip is to install via `pip install autogluon.tabular[lightgbm]==1.4.0`.
Fitting model: WeightedEnsemble_L2 ...
	Failed to import torch or check CUDA availability!Please ensure you have the correct version of PyTorch installed by running `pip install -U torch`
	Ensemble Weights: {'RandomForestMSE': 1.0}
	-0.1342	 = Validation score   (-pinball_loss)
	0.01s	 = Training   runtime
	0.0s	 = Validation runtime
AutoGluon training complete, total runtime = 1.31s ... Best model: WeightedEnsemble_L2 | Estimated inference throughput: 455.0 rows/s (16 batch size)
Disabling calibration for metric `pinball_loss` due to having fewer than 1000 rows of validation data for calibration, to avoid overfitting (16 rows). Force calibration via specifying `calibrate=True`. (calibrate='auto')
TabularPredictor saved. To load, use: predictor = TabularPredictor.load("/home/chandlernick/BHT/Research/conformal-data-cleaning/src/conformal_data_cleaning/AutogluonModels/feature_a")
2025-12-10 10:05:02,405 - INFO - conformal_data_cleaning.cleaner.autogluon: Start fitting predictor #2 of 5
2025-12-10 10:05:02,405 - INFO - conformal_data_cleaning.cleaner.autogluon: Start fitting predictor #2 of 5
Warning: path already exists! This predictor may overwrite an existing predictor! path="AutogluonModels/feature_b"
Verbosity: 2 (Standard Logging)
=================== System Info ===================
AutoGluon Version:  1.4.0
Python Version:     3.12.11
Operating System:   Linux
Platform Machine:   x86_64
Platform Version:   #88~22.04.1-Ubuntu SMP PREEMPT_DYNAMIC Tue Oct 14 14:03:14 UTC 2
CPU Count:          8
Memory Avail:       4.55 GB / 11.46 GB (39.7%)
Disk Space Avail:   155.50 GB / 467.89 GB (33.2%)
===================================================
No presets specified! To achieve strong results with AutoGluon, it is recommended to use the available presets. Defaulting to `'medium'`...
	Recommended Presets (For more details refer to https://auto.gluon.ai/stable/tutorials/tabular/tabular-essentials.html#presets):
	presets='extreme' : New in v1.4: Massively better than 'best' on datasets <30000 samples by using new models meta-learned on https://tabarena.ai: TabPFNv2, TabICL, Mitra, and TabM. Absolute best accuracy. Requires a GPU. Recommended 64 GB CPU memory and 32+ GB GPU memory.
	presets='best'    : Maximize accuracy. Recommended for most users. Use in competitions and benchmarks.
	presets='high'    : Strong accuracy with fast inference speed.
	presets='good'    : Good accuracy with very fast inference speed.
	presets='medium'  : Fast training time, ideal for initial prototyping.
Using hyperparameters preset: hyperparameters='default'
Beginning AutoGluon training ...
AutoGluon will save models to "/home/chandlernick/BHT/Research/conformal-data-cleaning/src/conformal_data_cleaning/AutogluonModels/feature_b"
Train Data Rows:    80
Train Data Columns: 4
Label Column:       feature_b
Problem Type:       quantile
Preprocessing data ...
Using Feature Generators to preprocess the data ...
Fitting AutoMLPipelineFeatureGenerator...
	Available Memory:                    4658.91 MB
	Train Data (Original)  Memory Usage: 0.00 MB (0.0% of available memory)
	Inferring data type of each feature based on column values. Set feature_metadata_in to manually specify special dtypes of the features.
	Stage 1 Generators:
		Fitting AsTypeFeatureGenerator...
			Note: Converting 1 features to boolean dtype as they only contain 2 unique values.
	Stage 2 Generators:
		Fitting FillNaFeatureGenerator...
	Stage 3 Generators:
		Fitting IdentityFeatureGenerator...
	Stage 4 Generators:
		Fitting DropUniqueFeatureGenerator...
	Stage 5 Generators:
		Fitting DropDuplicatesFeatureGenerator...
	Types of features in original data (raw dtype, special dtypes):
		('float', []) : 2 | ['feature_a', 'feature_d']
		('int', [])   : 2 | ['feature_c', 'feature_e']
	Types of features in processed data (raw dtype, special dtypes):
		('float', [])     : 2 | ['feature_a', 'feature_d']
		('int', [])       : 1 | ['feature_c']
		('int', ['bool']) : 1 | ['feature_e']
	0.0s = Fit runtime
	4 features in original data used to generate 4 features in processed data.
	Train Data (Processed) Memory Usage: 0.00 MB (0.0% of available memory)
Data preprocessing and feature engineering runtime = 0.02s ...
AutoGluon will gauge predictive performance using evaluation metric: 'pinball_loss'
	This metric's sign has been flipped to adhere to being higher_is_better. The metric score can be multiplied by -1 to get the metric value.
	To change this, specify the eval_metric parameter of Predictor()
Automatically generating train/validation split with holdout_frac=0.2, Train Rows: 64, Val Rows: 16
User-specified model hyperparameters to be fit:
{
	'NN_TORCH': [{}],
	'GBM': [{'extra_trees': True, 'ag_args': {'name_suffix': 'XT'}}, {}, {'learning_rate': 0.03, 'num_leaves': 128, 'feature_fraction': 0.9, 'min_data_in_leaf': 3, 'ag_args': {'name_suffix': 'Large', 'priority': 0, 'hyperparameter_tune_kwargs': None}}],
	'CAT': [{}],
	'XGB': [{}],
	'FASTAI': [{}],
	'RF': [{'criterion': 'gini', 'ag_args': {'name_suffix': 'Gini', 'problem_types': ['binary', 'multiclass']}}, {'criterion': 'entropy', 'ag_args': {'name_suffix': 'Entr', 'problem_types': ['binary', 'multiclass']}}, {'criterion': 'squared_error', 'ag_args': {'name_suffix': 'MSE', 'problem_types': ['regression', 'quantile']}}],
	'XT': [{'criterion': 'gini', 'ag_args': {'name_suffix': 'Gini', 'problem_types': ['binary', 'multiclass']}}, {'criterion': 'entropy', 'ag_args': {'name_suffix': 'Entr', 'problem_types': ['binary', 'multiclass']}}, {'criterion': 'squared_error', 'ag_args': {'name_suffix': 'MSE', 'problem_types': ['regression', 'quantile']}}],
}
Fitting 8 L1 models, fit_strategy="sequential" ...
Fitting model: LightGBMXT ...
	Failed to import torch or check CUDA availability!Please ensure you have the correct version of PyTorch installed by running `pip install -U torch`
	Fitting with cpus=4, gpus=0, mem=0.0/4.5 GB
	Warning: Exception caused LightGBMXT to fail during training (ImportError)... Skipping this model.
		`import lightgbm` failed. A quick tip is to install via `pip install autogluon.tabular[lightgbm]==1.4.0`.
Fitting model: LightGBM ...
	Failed to import torch or check CUDA availability!Please ensure you have the correct version of PyTorch installed by running `pip install -U torch`
	Fitting with cpus=4, gpus=0, mem=0.0/4.5 GB
	Warning: Exception caused LightGBM to fail during training (ImportError)... Skipping this model.
		`import lightgbm` failed. A quick tip is to install via `pip install autogluon.tabular[lightgbm]==1.4.0`.

[('preprocess', ColumnTransformer(sparse_threshold=0,
                  transformers=[('categorical_features',
                                 OneHotEncoder(handle_unknown='ignore'),
                                 ['feature_c', 'feature_e']),
                                ('scaled_numeric', StandardScaler(),
                                 ['feature_a', 'feature_b', 'feature_d'])])), ('predictor', <autogluon.tabular.predictor.predictor.TabularPredictor object at 0x70092242dbb0>)]

Fitting model: RandomForestMSE ...
	Failed to import torch or check CUDA availability!Please ensure you have the correct version of PyTorch installed by running `pip install -U torch`
	Fitting with cpus=8, gpus=0
	WARNING: RandomForestQuantileRegressor are experimental for quantile regression. They may change or be removed without warning in future releases.
	-0.4489	 = Validation score   (-pinball_loss)
	0.32s	 = Training   runtime
	0.03s	 = Validation runtime
Fitting model: CatBoost ...
	Failed to import torch or check CUDA availability!Please ensure you have the correct version of PyTorch installed by running `pip install -U torch`
	Fitting with cpus=4, gpus=0
	Warning: Exception caused CatBoost to fail during training (ImportError)... Skipping this model.
		`import catboost` failed. A quick tip is to install via `pip install autogluon.tabular[catboost]==1.4.0`.
Fitting model: ExtraTreesMSE ...
	Failed to import torch or check CUDA availability!Please ensure you have the correct version of PyTorch installed by running `pip install -U torch`
	Fitting with cpus=8, gpus=0
	WARNING: ExtraTreesQuantileRegressor are experimental for quantile regression. They may change or be removed without warning in future releases.
	-0.3906	 = Validation score   (-pinball_loss)
	0.32s	 = Training   runtime
	0.03s	 = Validation runtime
Fitting model: NeuralNetFastAI ...
	Failed to import torch or check CUDA availability!Please ensure you have the correct version of PyTorch installed by running `pip install -U torch`
	Fitting with cpus=4, gpus=0, mem=0.0/4.5 GB
	Warning: Exception caused NeuralNetFastAI to fail during training (ImportError)... Skipping this model.
		Import fastai failed. A quick tip is to install via `pip install autogluon.tabular[fastai]==1.4.0`.
Fitting model: NeuralNetTorch ...
	Failed to import torch or check CUDA availability!Please ensure you have the correct version of PyTorch installed by running `pip install -U torch`
	Fitting with cpus=4, gpus=0, mem=0.0/4.5 GB
	Warning: Exception caused NeuralNetTorch to fail during training (ImportError)... Skipping this model.
		Unable to import dependency torch
A quick tip is to install via `pip install torch`.
The minimum torch version is currently 2.2.
Fitting model: LightGBMLarge ...
	Failed to import torch or check CUDA availability!Please ensure you have the correct version of PyTorch installed by running `pip install -U torch`
	Fitting with cpus=4, gpus=0, mem=0.0/4.5 GB
	Warning: Exception caused LightGBMLarge to fail during training (ImportError)... Skipping this model.
		`import lightgbm` failed. A quick tip is to install via `pip install autogluon.tabular[lightgbm]==1.4.0`.
Fitting model: WeightedEnsemble_L2 ...
	Failed to import torch or check CUDA availability!Please ensure you have the correct version of PyTorch installed by running `pip install -U torch`
	Ensemble Weights: {'ExtraTreesMSE': 0.889, 'RandomForestMSE': 0.111}
	-0.3863	 = Validation score   (-pinball_loss)
	0.01s	 = Training   runtime
	0.0s	 = Validation runtime
AutoGluon training complete, total runtime = 1.27s ... Best model: WeightedEnsemble_L2 | Estimated inference throughput: 254.3 rows/s (16 batch size)
Disabling calibration for metric `pinball_loss` due to having fewer than 1000 rows of validation data for calibration, to avoid overfitting (16 rows). Force calibration via specifying `calibrate=True`. (calibrate='auto')
TabularPredictor saved. To load, use: predictor = TabularPredictor.load("/home/chandlernick/BHT/Research/conformal-data-cleaning/src/conformal_data_cleaning/AutogluonModels/feature_b")
2025-12-10 10:05:03,859 - INFO - conformal_data_cleaning.cleaner.autogluon: Start fitting predictor #3 of 5
2025-12-10 10:05:03,859 - INFO - conformal_data_cleaning.cleaner.autogluon: Start fitting predictor #3 of 5
Warning: path already exists! This predictor may overwrite an existing predictor! path="AutogluonModels/feature_c"
Verbosity: 2 (Standard Logging)
=================== System Info ===================
AutoGluon Version:  1.4.0
Python Version:     3.12.11
Operating System:   Linux
Platform Machine:   x86_64
Platform Version:   #88~22.04.1-Ubuntu SMP PREEMPT_DYNAMIC Tue Oct 14 14:03:14 UTC 2
CPU Count:          8
Memory Avail:       4.53 GB / 11.46 GB (39.5%)
Disk Space Avail:   155.50 GB / 467.89 GB (33.2%)
===================================================
No presets specified! To achieve strong results with AutoGluon, it is recommended to use the available presets. Defaulting to `'medium'`...
	Recommended Presets (For more details refer to https://auto.gluon.ai/stable/tutorials/tabular/tabular-essentials.html#presets):
	presets='extreme' : New in v1.4: Massively better than 'best' on datasets <30000 samples by using new models meta-learned on https://tabarena.ai: TabPFNv2, TabICL, Mitra, and TabM. Absolute best accuracy. Requires a GPU. Recommended 64 GB CPU memory and 32+ GB GPU memory.
	presets='best'    : Maximize accuracy. Recommended for most users. Use in competitions and benchmarks.
	presets='high'    : Strong accuracy with fast inference speed.
	presets='good'    : Good accuracy with very fast inference speed.
	presets='medium'  : Fast training time, ideal for initial prototyping.
Using hyperparameters preset: hyperparameters='default'
Beginning AutoGluon training ...
AutoGluon will save models to "/home/chandlernick/BHT/Research/conformal-data-cleaning/src/conformal_data_cleaning/AutogluonModels/feature_c"
Train Data Rows:    80
Train Data Columns: 4
Label Column:       feature_c
Problem Type:       multiclass
Preprocessing data ...
Warning: Updated label_count_threshold from 10 to 1 to avoid cutting too many classes.
Train Data Class Count: 11
Using Feature Generators to preprocess the data ...
Fitting AutoMLPipelineFeatureGenerator...
	Available Memory:                    4634.12 MB
	Train Data (Original)  Memory Usage: 0.00 MB (0.0% of available memory)
	Inferring data type of each feature based on column values. Set feature_metadata_in to manually specify special dtypes of the features.
	Stage 1 Generators:
		Fitting AsTypeFeatureGenerator...
			Note: Converting 1 features to boolean dtype as they only contain 2 unique values.
	Stage 2 Generators:
		Fitting FillNaFeatureGenerator...
	Stage 3 Generators:
		Fitting IdentityFeatureGenerator...
	Stage 4 Generators:
		Fitting DropUniqueFeatureGenerator...
	Stage 5 Generators:
		Fitting DropDuplicatesFeatureGenerator...
	Types of features in original data (raw dtype, special dtypes):
		('float', []) : 3 | ['feature_a', 'feature_b', 'feature_d']
		('int', [])   : 1 | ['feature_e']
	Types of features in processed data (raw dtype, special dtypes):
		('float', [])     : 3 | ['feature_a', 'feature_b', 'feature_d']
		('int', ['bool']) : 1 | ['feature_e']
	0.0s = Fit runtime
	4 features in original data used to generate 4 features in processed data.
	Train Data (Processed) Memory Usage: 0.00 MB (0.0% of available memory)
Data preprocessing and feature engineering runtime = 0.03s ...
AutoGluon will gauge predictive performance using evaluation metric: 'f1_macro'
	To change this, specify the eval_metric parameter of Predictor()
Automatically generating train/validation split with holdout_frac=0.2, Train Rows: 64, Val Rows: 16
User-specified model hyperparameters to be fit:
{
	'NN_TORCH': [{}],
	'GBM': [{'extra_trees': True, 'ag_args': {'name_suffix': 'XT'}}, {}, {'learning_rate': 0.03, 'num_leaves': 128, 'feature_fraction': 0.9, 'min_data_in_leaf': 3, 'ag_args': {'name_suffix': 'Large', 'priority': 0, 'hyperparameter_tune_kwargs': None}}],
	'CAT': [{}],
	'XGB': [{}],
	'FASTAI': [{}],
	'RF': [{'criterion': 'gini', 'ag_args': {'name_suffix': 'Gini', 'problem_types': ['binary', 'multiclass']}}, {'criterion': 'entropy', 'ag_args': {'name_suffix': 'Entr', 'problem_types': ['binary', 'multiclass']}}, {'criterion': 'squared_error', 'ag_args': {'name_suffix': 'MSE', 'problem_types': ['regression', 'quantile']}}],
	'XT': [{'criterion': 'gini', 'ag_args': {'name_suffix': 'Gini', 'problem_types': ['binary', 'multiclass']}}, {'criterion': 'entropy', 'ag_args': {'name_suffix': 'Entr', 'problem_types': ['binary', 'multiclass']}}, {'criterion': 'squared_error', 'ag_args': {'name_suffix': 'MSE', 'problem_types': ['regression', 'quantile']}}],
}
Fitting 11 L1 models, fit_strategy="sequential" ...
Fitting model: NeuralNetFastAI ...
	Failed to import torch or check CUDA availability!Please ensure you have the correct version of PyTorch installed by running `pip install -U torch`
	Fitting with cpus=4, gpus=0, mem=0.0/4.5 GB
	Warning: Exception caused NeuralNetFastAI to fail during training (ImportError)... Skipping this model.
		Import fastai failed. A quick tip is to install via `pip install autogluon.tabular[fastai]==1.4.0`.
Fitting model: LightGBMXT ...
	Failed to import torch or check CUDA availability!Please ensure you have the correct version of PyTorch installed by running `pip install -U torch`
	Fitting with cpus=4, gpus=0, mem=0.0/4.5 GB
	Warning: Exception caused LightGBMXT to fail during training (ImportError)... Skipping this model.
		`import lightgbm` failed. A quick tip is to install via `pip install autogluon.tabular[lightgbm]==1.4.0`.
Fitting model: LightGBM ...
	Failed to import torch or check CUDA availability!Please ensure you have the correct version of PyTorch installed by running `pip install -U torch`
	Fitting with cpus=4, gpus=0, mem=0.0/4.5 GB
	Warning: Exception caused LightGBM to fail during training (ImportError)... Skipping this model.
		`import lightgbm` failed. A quick tip is to install via `pip install autogluon.tabular[lightgbm]==1.4.0`.
Fitting model: RandomForestGini ...
	Failed to import torch or check CUDA availability!Please ensure you have the correct version of PyTorch installed by running `pip install -U torch`
	Fitting with cpus=8, gpus=0
	0.1071	 = Validation score   (f1_macro)
	0.68s	 = Training   runtime
	0.02s	 = Validation runtime
Fitting model: RandomForestEntr ...
	Failed to import torch or check CUDA availability!Please ensure you have the correct version of PyTorch installed by running `pip install -U torch`
	Fitting with cpus=8, gpus=0
	0.1131	 = Validation score   (f1_macro)
	0.67s	 = Training   runtime
	0.02s	 = Validation runtime
Fitting model: CatBoost ...
	Failed to import torch or check CUDA availability!Please ensure you have the correct version of PyTorch installed by running `pip install -U torch`
	Fitting with cpus=4, gpus=0
	Warning: Exception caused CatBoost to fail during training (ImportError)... Skipping this model.
		`import catboost` failed. A quick tip is to install via `pip install autogluon.tabular[catboost]==1.4.0`.
Fitting model: ExtraTreesGini ...
	Failed to import torch or check CUDA availability!Please ensure you have the correct version of PyTorch installed by running `pip install -U torch`
	Fitting with cpus=8, gpus=0
	0.0729	 = Validation score   (f1_macro)
	0.68s	 = Training   runtime
	0.02s	 = Validation runtime
Fitting model: ExtraTreesEntr ...
	Failed to import torch or check CUDA availability!Please ensure you have the correct version of PyTorch installed by running `pip install -U torch`
	Fitting with cpus=8, gpus=0
	0.1131	 = Validation score   (f1_macro)
	0.67s	 = Training   runtime
	0.02s	 = Validation runtime
Fitting model: XGBoost ...
	Failed to import torch or check CUDA availability!Please ensure you have the correct version of PyTorch installed by running `pip install -U torch`
	Fitting with cpus=4, gpus=0
	Warning: Exception caused XGBoost to fail during training (ImportError)... Skipping this model.
		`import xgboost` failed. A quick tip is to install via `pip install autogluon.tabular[xgboost]==1.4.0`.
Fitting model: NeuralNetTorch ...
	Failed to import torch or check CUDA availability!Please ensure you have the correct version of PyTorch installed by running `pip install -U torch`
	Fitting with cpus=4, gpus=0, mem=0.0/4.6 GB
	Warning: Exception caused NeuralNetTorch to fail during training (ImportError)... Skipping this model.
		Unable to import dependency torch
A quick tip is to install via `pip install torch`.
The minimum torch version is currently 2.2.
Fitting model: LightGBMLarge ...
	Failed to import torch or check CUDA availability!Please ensure you have the correct version of PyTorch installed by running `pip install -U torch`
	Fitting with cpus=4, gpus=0, mem=0.1/4.6 GB
	Warning: Exception caused LightGBMLarge to fail during training (ImportError)... Skipping this model.
		`import lightgbm` failed. A quick tip is to install via `pip install autogluon.tabular[lightgbm]==1.4.0`.
Fitting model: WeightedEnsemble_L2 ...
	Failed to import torch or check CUDA availability!Please ensure you have the correct version of PyTorch installed by running `pip install -U torch`
	Ensemble Weights: {'RandomForestEntr': 0.5, 'ExtraTreesEntr': 0.5}
	0.1214	 = Validation score   (f1_macro)
	0.09s	 = Training   runtime
	0.0s	 = Validation runtime
AutoGluon training complete, total runtime = 3.6s ... Best model: WeightedEnsemble_L2 | Estimated inference throughput: 328.8 rows/s (16 batch size)
TabularPredictor saved. To load, use: predictor = TabularPredictor.load("/home/chandlernick/BHT/Research/conformal-data-cleaning/src/conformal_data_cleaning/AutogluonModels/feature_c")
2025-12-10 10:05:07,624 - INFO - conformal_data_cleaning.cleaner.autogluon: Start fitting predictor #4 of 5
2025-12-10 10:05:07,624 - INFO - conformal_data_cleaning.cleaner.autogluon: Start fitting predictor #4 of 5
Ignoring 'problem_type' of given 'predictor_params' since it is already defined.
Warning: path already exists! This predictor may overwrite an existing predictor! path="AutogluonModels/feature_d"
Verbosity: 2 (Standard Logging)
=================== System Info ===================
AutoGluon Version:  1.4.0
Python Version:     3.12.11
Operating System:   Linux
Platform Machine:   x86_64
Platform Version:   #88~22.04.1-Ubuntu SMP PREEMPT_DYNAMIC Tue Oct 14 14:03:14 UTC 2
CPU Count:          8
Memory Avail:       4.64 GB / 11.46 GB (40.5%)
Disk Space Avail:   155.50 GB / 467.89 GB (33.2%)
===================================================
No presets specified! To achieve strong results with AutoGluon, it is recommended to use the available presets. Defaulting to `'medium'`...
	Recommended Presets (For more details refer to https://auto.gluon.ai/stable/tutorials/tabular/tabular-essentials.html#presets):
	presets='extreme' : New in v1.4: Massively better than 'best' on datasets <30000 samples by using new models meta-learned on https://tabarena.ai: TabPFNv2, TabICL, Mitra, and TabM. Absolute best accuracy. Requires a GPU. Recommended 64 GB CPU memory and 32+ GB GPU memory.
	presets='best'    : Maximize accuracy. Recommended for most users. Use in competitions and benchmarks.
	presets='high'    : Strong accuracy with fast inference speed.
	presets='good'    : Good accuracy with very fast inference speed.
	presets='medium'  : Fast training time, ideal for initial prototyping.
Using hyperparameters preset: hyperparameters='default'
Beginning AutoGluon training ...
AutoGluon will save models to "/home/chandlernick/BHT/Research/conformal-data-cleaning/src/conformal_data_cleaning/AutogluonModels/feature_d"
Train Data Rows:    80
Train Data Columns: 4
Label Column:       feature_d
Problem Type:       quantile
Preprocessing data ...
Using Feature Generators to preprocess the data ...
Fitting AutoMLPipelineFeatureGenerator...
	Available Memory:                    4751.58 MB
	Train Data (Original)  Memory Usage: 0.00 MB (0.0% of available memory)
	Inferring data type of each feature based on column values. Set feature_metadata_in to manually specify special dtypes of the features.
	Stage 1 Generators:
		Fitting AsTypeFeatureGenerator...
			Note: Converting 1 features to boolean dtype as they only contain 2 unique values.
	Stage 2 Generators:
		Fitting FillNaFeatureGenerator...
	Stage 3 Generators:
		Fitting IdentityFeatureGenerator...
	Stage 4 Generators:
		Fitting DropUniqueFeatureGenerator...
	Stage 5 Generators:
		Fitting DropDuplicatesFeatureGenerator...
	Types of features in original data (raw dtype, special dtypes):
		('float', []) : 2 | ['feature_a', 'feature_b']
		('int', [])   : 2 | ['feature_c', 'feature_e']
	Types of features in processed data (raw dtype, special dtypes):
		('float', [])     : 2 | ['feature_a', 'feature_b']
		('int', [])       : 1 | ['feature_c']
		('int', ['bool']) : 1 | ['feature_e']
	0.0s = Fit runtime
	4 features in original data used to generate 4 features in processed data.
	Train Data (Processed) Memory Usage: 0.00 MB (0.0% of available memory)
Data preprocessing and feature engineering runtime = 0.02s ...
AutoGluon will gauge predictive performance using evaluation metric: 'pinball_loss'
	This metric's sign has been flipped to adhere to being higher_is_better. The metric score can be multiplied by -1 to get the metric value.
	To change this, specify the eval_metric parameter of Predictor()
Automatically generating train/validation split with holdout_frac=0.2, Train Rows: 64, Val Rows: 16
User-specified model hyperparameters to be fit:
{
	'NN_TORCH': [{}],
	'GBM': [{'extra_trees': True, 'ag_args': {'name_suffix': 'XT'}}, {}, {'learning_rate': 0.03, 'num_leaves': 128, 'feature_fraction': 0.9, 'min_data_in_leaf': 3, 'ag_args': {'name_suffix': 'Large', 'priority': 0, 'hyperparameter_tune_kwargs': None}}],
	'CAT': [{}],
	'XGB': [{}],
	'FASTAI': [{}],
	'RF': [{'criterion': 'gini', 'ag_args': {'name_suffix': 'Gini', 'problem_types': ['binary', 'multiclass']}}, {'criterion': 'entropy', 'ag_args': {'name_suffix': 'Entr', 'problem_types': ['binary', 'multiclass']}}, {'criterion': 'squared_error', 'ag_args': {'name_suffix': 'MSE', 'problem_types': ['regression', 'quantile']}}],
	'XT': [{'criterion': 'gini', 'ag_args': {'name_suffix': 'Gini', 'problem_types': ['binary', 'multiclass']}}, {'criterion': 'entropy', 'ag_args': {'name_suffix': 'Entr', 'problem_types': ['binary', 'multiclass']}}, {'criterion': 'squared_error', 'ag_args': {'name_suffix': 'MSE', 'problem_types': ['regression', 'quantile']}}],
}
Fitting 8 L1 models, fit_strategy="sequential" ...
Fitting model: LightGBMXT ...
	Failed to import torch or check CUDA availability!Please ensure you have the correct version of PyTorch installed by running `pip install -U torch`
	Fitting with cpus=4, gpus=0, mem=0.0/4.6 GB
	Warning: Exception caused LightGBMXT to fail during training (ImportError)... Skipping this model.
		`import lightgbm` failed. A quick tip is to install via `pip install autogluon.tabular[lightgbm]==1.4.0`.
Fitting model: LightGBM ...
	Failed to import torch or check CUDA availability!Please ensure you have the correct version of PyTorch installed by running `pip install -U torch`
	Fitting with cpus=4, gpus=0, mem=0.0/4.6 GB
	Warning: Exception caused LightGBM to fail during training (ImportError)... Skipping this model.
		`import lightgbm` failed. A quick tip is to install via `pip install autogluon.tabular[lightgbm]==1.4.0`.

[('preprocess', ColumnTransformer(sparse_threshold=0,
                  transformers=[('categorical_features',
                                 OneHotEncoder(handle_unknown='ignore'),
                                 ['feature_c', 'feature_e']),
                                ('scaled_numeric', StandardScaler(),
                                 ['feature_a', 'feature_b', 'feature_d'])])), ('predictor', <autogluon.tabular.predictor.predictor.TabularPredictor object at 0x700920bc9670>)]

Fitting model: RandomForestMSE ...
	Failed to import torch or check CUDA availability!Please ensure you have the correct version of PyTorch installed by running `pip install -U torch`
	Fitting with cpus=8, gpus=0
	WARNING: RandomForestQuantileRegressor are experimental for quantile regression. They may change or be removed without warning in future releases.
	-0.3292	 = Validation score   (-pinball_loss)
	0.32s	 = Training   runtime
	0.03s	 = Validation runtime
Fitting model: CatBoost ...
	Failed to import torch or check CUDA availability!Please ensure you have the correct version of PyTorch installed by running `pip install -U torch`
	Fitting with cpus=4, gpus=0
	Warning: Exception caused CatBoost to fail during training (ImportError)... Skipping this model.
		`import catboost` failed. A quick tip is to install via `pip install autogluon.tabular[catboost]==1.4.0`.
Fitting model: ExtraTreesMSE ...
	Failed to import torch or check CUDA availability!Please ensure you have the correct version of PyTorch installed by running `pip install -U torch`
	Fitting with cpus=8, gpus=0
	WARNING: ExtraTreesQuantileRegressor are experimental for quantile regression. They may change or be removed without warning in future releases.
	-0.3344	 = Validation score   (-pinball_loss)
	0.3s	 = Training   runtime
	0.03s	 = Validation runtime
Fitting model: NeuralNetFastAI ...
	Failed to import torch or check CUDA availability!Please ensure you have the correct version of PyTorch installed by running `pip install -U torch`
	Fitting with cpus=4, gpus=0, mem=0.0/4.6 GB
	Warning: Exception caused NeuralNetFastAI to fail during training (ImportError)... Skipping this model.
		Import fastai failed. A quick tip is to install via `pip install autogluon.tabular[fastai]==1.4.0`.
Fitting model: NeuralNetTorch ...
	Failed to import torch or check CUDA availability!Please ensure you have the correct version of PyTorch installed by running `pip install -U torch`
	Fitting with cpus=4, gpus=0, mem=0.0/4.6 GB
	Warning: Exception caused NeuralNetTorch to fail during training (ImportError)... Skipping this model.
		Unable to import dependency torch
A quick tip is to install via `pip install torch`.
The minimum torch version is currently 2.2.
Fitting model: LightGBMLarge ...
	Failed to import torch or check CUDA availability!Please ensure you have the correct version of PyTorch installed by running `pip install -U torch`
	Fitting with cpus=4, gpus=0, mem=0.0/4.6 GB
	Warning: Exception caused LightGBMLarge to fail during training (ImportError)... Skipping this model.
		`import lightgbm` failed. A quick tip is to install via `pip install autogluon.tabular[lightgbm]==1.4.0`.
Fitting model: WeightedEnsemble_L2 ...
	Failed to import torch or check CUDA availability!Please ensure you have the correct version of PyTorch installed by running `pip install -U torch`
	Ensemble Weights: {'RandomForestMSE': 0.783, 'ExtraTreesMSE': 0.217}
	-0.3196	 = Validation score   (-pinball_loss)
	0.01s	 = Training   runtime
	0.0s	 = Validation runtime
AutoGluon training complete, total runtime = 1.26s ... Best model: WeightedEnsemble_L2 | Estimated inference throughput: 255.6 rows/s (16 batch size)
Disabling calibration for metric `pinball_loss` due to having fewer than 1000 rows of validation data for calibration, to avoid overfitting (16 rows). Force calibration via specifying `calibrate=True`. (calibrate='auto')
TabularPredictor saved. To load, use: predictor = TabularPredictor.load("/home/chandlernick/BHT/Research/conformal-data-cleaning/src/conformal_data_cleaning/AutogluonModels/feature_d")
2025-12-10 10:05:09,064 - INFO - conformal_data_cleaning.cleaner.autogluon: Start fitting predictor #5 of 5
2025-12-10 10:05:09,064 - INFO - conformal_data_cleaning.cleaner.autogluon: Start fitting predictor #5 of 5
Warning: path already exists! This predictor may overwrite an existing predictor! path="AutogluonModels/feature_e"
Verbosity: 2 (Standard Logging)
=================== System Info ===================
AutoGluon Version:  1.4.0
Python Version:     3.12.11
Operating System:   Linux
Platform Machine:   x86_64
Platform Version:   #88~22.04.1-Ubuntu SMP PREEMPT_DYNAMIC Tue Oct 14 14:03:14 UTC 2
CPU Count:          8
Memory Avail:       4.64 GB / 11.46 GB (40.5%)
Disk Space Avail:   155.50 GB / 467.89 GB (33.2%)
===================================================
No presets specified! To achieve strong results with AutoGluon, it is recommended to use the available presets. Defaulting to `'medium'`...
	Recommended Presets (For more details refer to https://auto.gluon.ai/stable/tutorials/tabular/tabular-essentials.html#presets):
	presets='extreme' : New in v1.4: Massively better than 'best' on datasets <30000 samples by using new models meta-learned on https://tabarena.ai: TabPFNv2, TabICL, Mitra, and TabM. Absolute best accuracy. Requires a GPU. Recommended 64 GB CPU memory and 32+ GB GPU memory.
	presets='best'    : Maximize accuracy. Recommended for most users. Use in competitions and benchmarks.
	presets='high'    : Strong accuracy with fast inference speed.
	presets='good'    : Good accuracy with very fast inference speed.
	presets='medium'  : Fast training time, ideal for initial prototyping.
Using hyperparameters preset: hyperparameters='default'
Beginning AutoGluon training ...
AutoGluon will save models to "/home/chandlernick/BHT/Research/conformal-data-cleaning/src/conformal_data_cleaning/AutogluonModels/feature_e"
Train Data Rows:    80
Train Data Columns: 4
Label Column:       feature_e
Problem Type:       binary
Preprocessing data ...
Selected class <--> label mapping:  class 1 = 1, class 0 = 0
Using Feature Generators to preprocess the data ...
Fitting AutoMLPipelineFeatureGenerator...
	Available Memory:                    4746.51 MB
	Train Data (Original)  Memory Usage: 0.00 MB (0.0% of available memory)
	Inferring data type of each feature based on column values. Set feature_metadata_in to manually specify special dtypes of the features.
	Stage 1 Generators:
		Fitting AsTypeFeatureGenerator...
	Stage 2 Generators:
		Fitting FillNaFeatureGenerator...
	Stage 3 Generators:
		Fitting IdentityFeatureGenerator...
	Stage 4 Generators:
		Fitting DropUniqueFeatureGenerator...
	Stage 5 Generators:
		Fitting DropDuplicatesFeatureGenerator...
	Types of features in original data (raw dtype, special dtypes):
		('float', []) : 3 | ['feature_a', 'feature_b', 'feature_d']
		('int', [])   : 1 | ['feature_c']
	Types of features in processed data (raw dtype, special dtypes):
		('float', []) : 3 | ['feature_a', 'feature_b', 'feature_d']
		('int', [])   : 1 | ['feature_c']
	0.0s = Fit runtime
	4 features in original data used to generate 4 features in processed data.
	Train Data (Processed) Memory Usage: 0.00 MB (0.0% of available memory)
Data preprocessing and feature engineering runtime = 0.02s ...
AutoGluon will gauge predictive performance using evaluation metric: 'f1'
	To change this, specify the eval_metric parameter of Predictor()
Automatically generating train/validation split with holdout_frac=0.2, Train Rows: 64, Val Rows: 16
User-specified model hyperparameters to be fit:
{
	'NN_TORCH': [{}],
	'GBM': [{'extra_trees': True, 'ag_args': {'name_suffix': 'XT'}}, {}, {'learning_rate': 0.03, 'num_leaves': 128, 'feature_fraction': 0.9, 'min_data_in_leaf': 3, 'ag_args': {'name_suffix': 'Large', 'priority': 0, 'hyperparameter_tune_kwargs': None}}],
	'CAT': [{}],
	'XGB': [{}],
	'FASTAI': [{}],
	'RF': [{'criterion': 'gini', 'ag_args': {'name_suffix': 'Gini', 'problem_types': ['binary', 'multiclass']}}, {'criterion': 'entropy', 'ag_args': {'name_suffix': 'Entr', 'problem_types': ['binary', 'multiclass']}}, {'criterion': 'squared_error', 'ag_args': {'name_suffix': 'MSE', 'problem_types': ['regression', 'quantile']}}],
	'XT': [{'criterion': 'gini', 'ag_args': {'name_suffix': 'Gini', 'problem_types': ['binary', 'multiclass']}}, {'criterion': 'entropy', 'ag_args': {'name_suffix': 'Entr', 'problem_types': ['binary', 'multiclass']}}, {'criterion': 'squared_error', 'ag_args': {'name_suffix': 'MSE', 'problem_types': ['regression', 'quantile']}}],
}
Fitting 11 L1 models, fit_strategy="sequential" ...
Fitting model: LightGBMXT ...
	Failed to import torch or check CUDA availability!Please ensure you have the correct version of PyTorch installed by running `pip install -U torch`
	Fitting with cpus=4, gpus=0, mem=0.0/4.6 GB
	Warning: Exception caused LightGBMXT to fail during training (ImportError)... Skipping this model.
		`import lightgbm` failed. A quick tip is to install via `pip install autogluon.tabular[lightgbm]==1.4.0`.
Fitting model: LightGBM ...
	Failed to import torch or check CUDA availability!Please ensure you have the correct version of PyTorch installed by running `pip install -U torch`
	Fitting with cpus=4, gpus=0, mem=0.0/4.6 GB
	Warning: Exception caused LightGBM to fail during training (ImportError)... Skipping this model.
		`import lightgbm` failed. A quick tip is to install via `pip install autogluon.tabular[lightgbm]==1.4.0`.
Fitting model: RandomForestGini ...
	Failed to import torch or check CUDA availability!Please ensure you have the correct version of PyTorch installed by running `pip install -U torch`
	Fitting with cpus=8, gpus=0
	0.2222	 = Validation score   (f1)
	0.35s	 = Training   runtime
	0.02s	 = Validation runtime
Fitting model: RandomForestEntr ...
	Failed to import torch or check CUDA availability!Please ensure you have the correct version of PyTorch installed by running `pip install -U torch`
	Fitting with cpus=8, gpus=0
	0.25	 = Validation score   (f1)
	0.36s	 = Training   runtime
	0.02s	 = Validation runtime
Fitting model: CatBoost ...
	Failed to import torch or check CUDA availability!Please ensure you have the correct version of PyTorch installed by running `pip install -U torch`
	Fitting with cpus=4, gpus=0
	Warning: Exception caused CatBoost to fail during training (ImportError)... Skipping this model.
		`import catboost` failed. A quick tip is to install via `pip install autogluon.tabular[catboost]==1.4.0`.
Fitting model: ExtraTreesGini ...
	Failed to import torch or check CUDA availability!Please ensure you have the correct version of PyTorch installed by running `pip install -U torch`
	Fitting with cpus=8, gpus=0
	0.2857	 = Validation score   (f1)
	0.36s	 = Training   runtime
	0.02s	 = Validation runtime
Fitting model: ExtraTreesEntr ...
	Failed to import torch or check CUDA availability!Please ensure you have the correct version of PyTorch installed by running `pip install -U torch`
	Fitting with cpus=8, gpus=0
	0.3333	 = Validation score   (f1)
	0.38s	 = Training   runtime
	0.02s	 = Validation runtime
Fitting model: NeuralNetFastAI ...
	Failed to import torch or check CUDA availability!Please ensure you have the correct version of PyTorch installed by running `pip install -U torch`
	Fitting with cpus=4, gpus=0, mem=0.0/4.6 GB
	Warning: Exception caused NeuralNetFastAI to fail during training (ImportError)... Skipping this model.
		Import fastai failed. A quick tip is to install via `pip install autogluon.tabular[fastai]==1.4.0`.
Fitting model: XGBoost ...
	Failed to import torch or check CUDA availability!Please ensure you have the correct version of PyTorch installed by running `pip install -U torch`
	Fitting with cpus=4, gpus=0
	Warning: Exception caused XGBoost to fail during training (ImportError)... Skipping this model.
		`import xgboost` failed. A quick tip is to install via `pip install autogluon.tabular[xgboost]==1.4.0`.
Fitting model: NeuralNetTorch ...
	Failed to import torch or check CUDA availability!Please ensure you have the correct version of PyTorch installed by running `pip install -U torch`
	Fitting with cpus=4, gpus=0, mem=0.0/4.6 GB
	Warning: Exception caused NeuralNetTorch to fail during training (ImportError)... Skipping this model.
		Unable to import dependency torch
A quick tip is to install via `pip install torch`.
The minimum torch version is currently 2.2.
Fitting model: LightGBMLarge ...
	Failed to import torch or check CUDA availability!Please ensure you have the correct version of PyTorch installed by running `pip install -U torch`
	Fitting with cpus=4, gpus=0, mem=0.0/4.6 GB
	Warning: Exception caused LightGBMLarge to fail during training (ImportError)... Skipping this model.
		`import lightgbm` failed. A quick tip is to install via `pip install autogluon.tabular[lightgbm]==1.4.0`.
Fitting model: WeightedEnsemble_L2 ...
	Failed to import torch or check CUDA availability!Please ensure you have the correct version of PyTorch installed by running `pip install -U torch`
	Ensemble Weights: {'ExtraTreesEntr': 1.0}
	0.3333	 = Validation score   (f1)
	0.1s	 = Training   runtime
	0.0s	 = Validation runtime
AutoGluon training complete, total runtime = 2.31s ... Best model: WeightedEnsemble_L2 | Estimated inference throughput: 657.3 rows/s (16 batch size)
Disabling decision threshold calibration for metric `f1` due to having fewer than 50 rows of validation data for calibration to avoid overfitting (16 rows). Force calibration via specifying `calibrate_decision_threshold=True`.
TabularPredictor saved. To load, use: predictor = TabularPredictor.load("/home/chandlernick/BHT/Research/conformal-data-cleaning/src/conformal_data_cleaning/AutogluonModels/feature_e")
WARNING: Int features without null values at train time contain null values at inference time! Imputing nulls to 0. To avoid this, pass the features as floats during fit!
WARNING: Int features with nulls: ['feature_c']

In [4]:
data, mask = cleaned_data

In [5]:
(data != df_error).sum()

feature_a    17
feature_b    13
feature_c    20
feature_d     9
feature_e     0
dtype: int64

In [6]:
mask.sum()

feature_a    17
feature_b    13
feature_c    20
feature_d     9
feature_e     0
dtype: int64